### ISSUE TITLE
student 삭제 오타

### ISSUE THREAD

**Issue by blxckdog7702** [hmu332233/dictation-server#1]
`/teachers/:teacher_id/students/:student_id`  
수정하기

**Comment by hmu332233** [comment]
`student_id` 속성 누락된것도 추가하기

**Comment by hmu332233** [comment]
[수정할 위치](https://github.com/hmu332233/dictation-server/blob/master/doc/api_list.md#student)  
여기였는데 이미 고친듯..? 아닌가

**Comment by blxckdog7702** [comment]
확인하세요 당장

**Comment by hmu332233** [comment]
확인해보니까  
`/teachers/:teacher_id/students/student_id` -> `/teachers/:teacher_id/students/:student_id`  
인데 수정하기 귀찮으니까 너가 수정해서 PR 날려줭  
너 내 contributor가 되라!

**Comment by hmu332233** [comment]
아 그리고 commit message에 `#2` 붙이는거 잊지말고  
그래야 확인하기 편함

**Comment by blxckdog7702** [comment]
#7 오타수정 PR 날렸어요
