### ISSUE TITLE
[선생님] addTeacherQuiz 시 Quiz의 number에 대한 issue

### ISSUE THREAD

**Issue by blxckdog7702** [hmu332233/dictation-server#14]
새로운 Quiz를 만들 때, 번호가 중복되지 않아야 한다.
사람이 일일이 번호를 기억해서 중복을 피하기는 힘드므로,
선생님에서 요청을 보낼 때, Quiz.number = null로 보내고, 서버에서 넘버링해준다.

**Comment by hmu332233** [comment]
https://github.com/hmu332233/dictation-server/commit/d8938e5a05616670f5462809593ced68c70e2527

위의 커밋으로 해결되었으니 close issue 합니다
